# fibjs
FROM exiaolv/fibjs:v034

# Create and change to the app directory.
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure both package.json AND package-lock.json are copied.
# Copying this separately prevents re-running npm install on every code change.
COPY package*.json ./

# Install production dependencies.
RUN fibjs --install --only=production

# Copy local code to the container image.
COPY . ./

# Run the web service on container startup.  docker run -it -d -p 0.0.0.0:8100:8100 app
CMD [ "fibjs", "index.js" ]